[Variables]
; Default font, Karla, supports only english
Font=Karla
; Your UTC offset (ex: -3, 0, 8...) https://www.timeanddate.com/time/map/
UTCOffset=-4

; By default, the progress bar fills up as the event goes, set this measure to 1 to invert it (make bar decrease as event goes)
InvertProgress=0

; This scales the whole skin (can be decimal, but not negative)
Size=0.8

; -------- CHANGE TEXT --------
; To change language, change these variables:

; Changes text before timer
StartText=Starts in
EndText=Ends in
; Text when event hasn't started
EventNotStarted= Event not started
; Changes the text in the timer
; if you want a space before/after the text, add it before/after and wrap the text in double quotes ex: " m "
; Default example: 4d 1h 43m 23s
Day="d "
Hour="h "
Minute="m "
Second="s"

; Change event type text
Story=Story
ChallengeLive=Challenge Live
VersusLive=VS Live
LiveGoals=Live Goals
MissionLive=Mission Live

;Change attribute text
Happy=Happy
Pure=Pure
Cool=Cool
Powerful=Powerful
StudioTickets=Studio Ticket
Coins=Coins
; ============================================================ JP SERVER ============================================================
; Title of the card
TitleJP=JP Event Info
; ============================================================ WW SERVER ============================================================

; Available display languages (banner or logo, not event name!): jp, tw, kr, en
ENImageDisplayLang=en
; Choose between banner or logo image (img or logo)
ENImage=logo

; Title of the card
TitleEN=EN Event Info
; ============================================================ TW SERVER ============================================================

; Available display languages (banner or logo, not event name!): jp, tw
TWImageDisplayLang=tw
; Choose between banner or logo image (img or logo)
TWImage=logo

; Title of the card
TitleTW=TW Event Info
; ============================================================ CN SERVER ============================================================

; Available display languages (banner or logo, not event name!): jp, tw, kr, en, cn
CNImageDisplayLang=cn
; Choose between banner or logo image (img or logo)
CNImage=logo

; Title of the card
TitleCN=CN Event Info
; ============================================================ KR SERVER ============================================================

; Available display languages (banner or logo, not event name!): jp, tw, kr
KRImageDisplayLang=kr
; Choose between banner or logo image (img or logo)
KRImage=logo

; Title of the card
TitleKR=KR Event Info
