[Variables]
; Default font, Karla, supports only english
Font=Karla
; Your UTC offset (ex: -3, 0, 8...) https://www.timeanddate.com/time/map/
UTCOffset=7

; By default, the progress bar fills up as the event goes, set this measure to 1 to invert it (make bar decrease as event goes)
InvertProgress=0

; This scales the whole skin (can be decimal, but not negative)
Size=0.7

; -------- CHANGE TEXT --------
; To change language, change these variables:

; Changes text before timer
StartText=Starts in
EndText=Ends in
; Text when event hasn't started
EventNotStarted= Event not started
; Changes the text in the timer
; if you want a space before/after the text, add it before/after and wrap the text in double quotes ex: " m "
; Default example: 4d 1h 43m 23s
Day="d "
Hour="h "
Minute="m "
Second="s"

; Change event type text
Story=Story
ChallengeLive=Challenge Live
VersusLive=VS Live
LiveGoals=Live Goals
MissionLive=Mission Live
Festival=Team Live Festival
Medley=Medley Live

;Change attribute text
Happy=Happy
Pure=Pure
Cool=Cool
Powerful=Powerful
StudioTickets=Studio Ticket
Coins=Coins
; ========================================= JP SERVER =========================================
JPImageDisplayLang=jp

; Title of the card
TitleJP=JP Event Info

; Choose between banner or logo image (img or logo)
JPImage=img

; Background color
JPBGColor=255,255,255

; Border color
JPBorderColor=207,207,207

; Text color
JPTextColor=80,80,80

; ========================================= WW SERVER =========================================

; Available display languages (banner or logo, not event name!): jp, tw, kr, en
ENImageDisplayLang=en
; Choose between banner or logo image (img or logo)
ENImage=img

; Title of the card
TitleEN=EN Event Info

; Background color
ENBGColor=255,255,255

; Border color
ENBorderColor=207,207,207

; Text color
ENTextColor=80,80,80

; ========================================= TW SERVER =========================================

; Available display languages (banner or logo, not event name!): jp, tw
TWImageDisplayLang=tw
; Choose between banner or logo image (img or logo)
TWImage=img

; Title of the card
TitleTW=TW Event Info

; Background color
TWBGColor=255,255,255

; Border color
TWBorderColor=207,207,207

; Text color
TWTextColor=80,80,80

; ========================================= CN SERVER =========================================

; Available display languages (banner or logo, not event name!): jp, tw, kr, en, cn
CNImageDisplayLang=cn
; Choose between banner or logo image (img or logo)
CNImage=img

; Title of the card
TitleCN=CN Event Info

; Background color
CNBGColor=255,255,255

; Border color
CNBorderColor=207,207,207

; Text color
CNTextColor=80,80,80

; ========================================= KR SERVER =========================================

; Available display languages (banner or logo, not event name!): jp, tw, kr
KRImageDisplayLang=kr
; Choose between banner or logo image (img or logo)
KRImage=img

; Title of the card
TitleKR=KR Event Info

; Background color
KRBGColor=255,255,255

; Border color
KRBorderColor=207,207,207

; Text color
KRTextColor=80,80,80
